name: CI Checking

on:
  pull_request:
    paths:
    - '**/*.md'

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2
        with:
          verbose: true
          incremental_files_only: false
          files: |
            *.md
            **/*.md