name: Validate Full Build for Ubuntu22.04

on:
  workflow_dispatch:

jobs:
  build_package:
    name: Build TDX Stack for Ubuntu 22.04
    runs-on: self-hosted
    steps:
      - name: Cleanup workspace for the job (self hosted only)
        run: |
          sudo rm -fr * .* || true

      - name: Check out PR
        uses: actions/checkout@v3

      - name: Build the source and binary packages
        run: |
          cd build/ubuntu-22.04/
          ./pkg-builder build-repo.sh

      - name: Generate guest image
        run: |
          cd build/ubuntu-22.04/guest-image/
          sudo ./create-ubuntu-image.sh -f -r ../guest_repo

